import Link from "next/link"

export default function Privacy(){
    return <div>
        <div className="page-header">
            <h2>Privacy Policy {"&"} Disclaimers</h2>
            <p>Last Updated 8/11/2021</p>
        </div>
        <section id="privacy-and-disclaimer">
            <h2>Privacy Policy</h2>
            <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use the
                Service and tells You about Your privacy rights and how the law protects
                You.
            </p>
            <p>
                We use Your Personal data to provide and improve the Service. By using
                the Service, You agree to the collection and use of information in
                accordance with this Privacy Policy.
            </p>
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>
                The words of which the initial letter is capitalized have meanings
                defined under the following conditions. The following definitions shall
                have the same meaning regardless of whether they appear in singular or
                in plural.
            </p>
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li>
                <p>
                    <strong>Organization</strong> (referred to as either &quot;the
                    Organization&quot;, &quot;We&quot;, &quot;Us&quot; or
                    &quot;Our&quot; in this Agreement) refers to The New Maps Project.
                </p>
                </li>
                <li>
                <p>
                    <strong>Cookies</strong> are small files that are placed on Your
                    computer, mobile device or any other device by a website, containing
                    the details of Your browsing history on that website among its many
                    uses.
                </p>
                </li>
                <li>
                <p>
                    <strong>Country</strong> refers to United States of America
                </p>
                </li>
                <li>
                <p>
                    <strong>Device</strong> means any device that can access the Service
                    such as a computer, a cellphone or a digital tablet.
                </p>
                </li>
                <li>
                <p>
                    <strong>Personal Data</strong> is any information that relates to an
                    identified or identifiable individual.
                </p>
                </li>
                <li>
                <p>
                    <strong>Service</strong> refers to the Website.
                </p>
                </li>
                <li>
                <p>
                    <strong>Service Provider</strong> means any natural or legal person
                    who processes the data on behalf of the Organization. It refers to
                    third-party companies or individuals employed by the Organization to
                    facilitate the Service, to provide the Service on behalf of the
                    Organization, to perform services related to the Service or to
                    assist the Organization in analyzing how the Service is used.
                </p>
                </li>
                <li>
                <p>
                    <strong>Usage Data</strong> refers to data collected automatically,
                    either generated by the use of the Service or from the Service
                    infrastructure itself (for example, the duration of a page visit).
                </p>
                </li>
                <li>
                <p>
                    <strong>Website</strong> refers to The New Maps Project, accessible
                    from{" "}
                    <a
                    href="https://thenewmapsproject.org"
                    rel="external nofollow noopener"
                    
                    >
                    https://thenewmapsproject.org
                    </a>
                </p>
                </li>
                <li>
                <p>
                    <strong>You</strong> means the individual accessing or using the
                    Service, or the company, or other legal entity on behalf of which
                    such individual is accessing or using the Service, as applicable.
                </p>
                </li>
            </ul>
            <h3>Types of Data Collected</h3>
            <h4>Usage Data</h4>
            <p>
                Usage Data may include information such as Your Device's Internet
                Protocol address (e.g. IP address), browser type, browser version, the
                pages of our Service that You visit, the time and date of Your visit,
                the time spent on those pages, unique device identifiers and other
                diagnostic data.
            </p>
            <p>
                When You access the Service by or through a mobile device, We may
                collect certain information automatically, including, but not limited
                to, the type of mobile device You use, Your mobile device unique ID, the
                IP address of Your mobile device, Your mobile operating system, the type
                of mobile Internet browser You use, unique device identifiers and other
                diagnostic data.
            </p>
            <p>
                We may also collect information that Your browser sends whenever You
                visit our Service or when You access the Service by or through a mobile
                device.
            </p>
            <h4>Tracking Technologies and Cookies</h4>
            <p>
                We use Cookies and similar tracking technologies to track the activity
                on Our Service and store certain information. Tracking technologies used
                are beacons, tags, and scripts to collect and track information and to
                improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul>
                <li>
                <strong>Browser Cookies</strong> You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if You do not accept Cookies, You may not be able to use some
                parts of our Service. Unless you have adjusted Your browser setting so
                that it will refuse Cookies, our Service may use Cookies.
                </li>
            </ul>
            <h3>Use of Usage Data</h3>
            <p>The Organization may use Personal Data for the following purposes:</p>
            <ul>
                <li>
                <p>
                    <strong>To provide and maintain our Service</strong>, including to
                    monitor the usage of our Service.
                </p>
                </li>

                <li>
                <p>
                    <strong>For other purposes</strong>: We may use Your information for
                    other purposes, such as data analysis, identifying usage trends,
                    determining the effectiveness of our promotional campaigns and to
                    evaluate and improve our Service, products, services, marketing and
                    your experience.
                </p>
                </li>
            </ul>
            <h3>Retention of Data</h3>
            <p>
                We will retain Usage Data for internal analysis purposes. Usage
                Data is generally retained for a shorter period of time, except when
                this data is used to strengthen the security or to improve the
                functionality of Our Service, or We are legally obligated to retain this
                data for longer time periods.
            </p>
            <h3>Disclosure of Data</h3>
            <h4>Law enforcement</h4>
            <p>
                Under certain circumstances, the Organization may be required to
                disclose Your Personal Data if required to do so by law or in response
                to valid requests by public authorities (e.g. a court or a government
                agency).
            </p>
            <h4>Other legal requirements</h4>
            <p>
                The Organization may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
            </p>
            <ul>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Organization</li>
                <li>
                Prevent or investigate possible wrongdoing in connection with the
                Service
                </li>
                <li>
                Protect the personal safety of Users of the Service or the public
                </li>
                <li>Protect against legal liability</li>
            </ul>
            <h3>Security of Your Data</h3>
            <p>
                The security of Your Personal Data is important to Us, but remember that
                no method of transmission over the Internet, or method of electronic
                storage is 100% secure. While We strive to use commercially acceptable
                means to protect Your Personal Data, We cannot guarantee its absolute
                security.
            </p>
            <h2>Children's Privacy</h2>
            <p>
                Our Service does not address anyone under the age of 13. We do not
                knowingly collect personally identifiable information from anyone under
                the age of 13. If You are a parent or guardian and You are aware that
                Your child has provided Us with Personal Data, please contact Us. If We
                become aware that We have collected Personal Data from anyone under the
                age of 13 without verification of parental consent, We take steps to
                remove that information from Our servers.
            </p>
            <p>
                If We need to rely on consent as a legal basis for processing Your
                information and Your country requires consent from a parent, We may
                require Your parent's consent before We collect and use that
                information.
            </p>
            <h2>Links to Other Websites</h2>
            <p>
                Our Service may contain links to other websites that are not operated by
                Us. If You click on a third party link, You will be directed to that
                third party's site. We strongly advise You to review the Privacy Policy
                of every site You visit.
            </p>
            <p>
                We have no control over and assume no responsibility for the content,
                privacy policies or practices of any third party sites or services.
            </p>
            <h2>Disclaimers</h2>

            <p>
                If you require any more information or have any questions about this
                site's disclaimers, please contact us.</p>

            <h3>Disclaimers for The New Maps Project</h3>

            <p>
                All the information on this website - https://thenewmapsproject.org - is
                published in good faith and for general information, example and
                demonstration purposes only. The New Maps Project does not make any
                warranties about the completeness, reliability and accuracy of this
                information. Any action you take upon the information you find on this
                website (The New Maps Project), is strictly at your own risk. The New
                Maps Project will not be liable for any losses and/or damages in
                connection with the use of our website.
            </p>

            <p>
                From our website, you can visit other websites by following hyperlinks
                to such external sites. While we strive to provide only quality links to
                useful and ethical websites, we have no control over the content and
                nature of these sites. These links to other websites do not imply a
                recommendation for all the content found on these sites. Site owners and
                content may change without notice and may occur before we have the
                opportunity to remove a link which may have gone 'bad'.
            </p>

            <p>
                Please be also aware that when you leave our website, other sites may
                have different privacy policies and terms which are beyond our control.
                Please be sure to check the Privacy Policies of these sites before
                engaging with the website or uploading any information.
            </p>

            <h3>Consent</h3>

            <p>
                By using our website, you hereby consent to our disclaimer and agree to
                its terms.
            </p>

            <h2>Updates</h2>

            <p>
                Should we update, amend or make any changes to this document, those
                changes will be posted on this page, and will take effect at
                the time the changes are posted on this page.
            </p>
            <h2>Contact</h2>
            <p>Contact information is here: <Link href="/contact" style={{color: "green", textDecoration: "underline"}}>contact page</Link> </p>
        </section>
    </div>
}